run_name: null
data_path: ${hydra:runtime.cwd}/data

model:
  name: DeepLabV3+
  encoder_name: efficientnet-b4
  in_channels: 3
  classes: ['background', 'lawn', 'paving']
  loss_func: FocalDice
  lr: 1e-3

datamodule:
  data_path: ${data_path}

checkpoints:
  ckpt_filename: DeepLabV3+_efficientnet-b4_focal-dice

trainer:
  resume_from_checkpoint: null
  precision: bf16-mixed
  max_epochs: 100

logger:
  api_key: ${oc.env:NEPTUNE_API_TOKEN}
  project: 2acholsk1-workspaces/2acholsk1-project
  log_model_checkpoints: false
  name: ${run_name}